version: "3.9"

services:
  mysql:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: core_database
      MYSQL_ROOT_HOST: "%"
      TZ: ${TZ:-UTC}
