micronaut:
  application:
    name: kullki-backend
datasources:
  default:
    url: jdbc:mysql://localhost:3306/core_database
    username: root
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
liquibase:
  datasources:
    default:
      change-log: classpath:database/liquibase-changelog.xml
